<template>
  <section id="map" class="map">
  </section>
</template>

<script>
import { default as LMap } from './LMap/LMap'
import { Point } from 'ol/geom'
import { Feature } from 'ol'
import VectorSource from 'ol/source/Vector'
import { Heatmap as HeatmapLayer } from 'ol/layer'

export default {
  name: 'Index',
  data() {
    return {
      LMap: null,
      heatMapLayer: null
    }
  },
  mounted() {
    this.LMap = new LMap({ center: [118.281041, 33.962096] })
    setTimeout(() => {
      const data = [
        {
          'total': 69,
          'address': '',
          'lng': '118.281041',
          'idle': 56,
          'contactName': '',
          'busy': 13,
          'name': '豪域西巷（洪泽湖路至骆马湖路）',
          'keyId': '117',
          'contactPhone': '',
          'lat': '33.962096'
        }, {
          'total': 69,
          'address': '',
          'lng': '118.294699',
          'idle': 62,
          'contactName': '',
          'busy': 7,
          'name': '黄河路（八一路至洪泽湖路）西',
          'keyId': '60',
          'contactPhone': '',
          'lat': '33.959553'
        }, {
          'total': 67,
          'address': '',
          'lng': '118.274658',
          'idle': 54,
          'contactName': '',
          'busy': 13,
          'name': '\t浦东路（发展大道至人民大道）',
          'keyId': '57',
          'contactPhone': '',
          'lat': '33.934377'
        }, {
          'total': 58,
          'address': '',
          'lng': '118.276189',
          'idle': 58,
          'contactName': '',
          'busy': 0,
          'name': '发展大道（深圳路至汕头路）东',
          'keyId': '87',
          'contactPhone': '',
          'lat': '33.92138'
        }, {
          'total': 56,
          'address': '',
          'lng': '0',
          'idle': 24,
          'contactName': '',
          'busy': 32,
          'name': '洪泽湖路（世纪大道至迎宾大道）南侧',
          'keyId': '38',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 54,
          'address': '',
          'lng': '118.278193',
          'idle': 37,
          'contactName': '',
          'busy': 17,
          'name': '发展大道（洞庭湖路至微山湖路）西',
          'keyId': '86',
          'contactPhone': '',
          'lat': '33.954016'
        }, {
          'total': 54,
          'address': '',
          'lng': '118.292301',
          'idle': 24,
          'contactName': '',
          'busy': 30,
          'name': '饮马堤路（项王路至杨公路）西',
          'keyId': '179',
          'contactPhone': '',
          'lat': '33.939144'
        }, {
          'total': 54,
          'address': '',
          'lng': '118.295568',
          'idle': 35,
          'contactName': '',
          'busy': 19,
          'name': '黄河路（城北路至宿支路）西',
          'keyId': '135',
          'contactPhone': '',
          'lat': '33.974985'
        }, {
          'total': 54,
          'address': '',
          'lng': '118.331987',
          'idle': 19,
          'contactName': '',
          'busy': 35,
          'name': '江山大道（洪泽湖路至五台山路）东',
          'keyId': '77',
          'contactPhone': '',
          'lat': '33.95569'
        }, {
          'total': 51,
          'address': '',
          'lng': '0',
          'idle': 43,
          'contactName': '',
          'busy': 8,
          'name': '洪泽湖路（平安大道至世纪大道）北',
          'keyId': '85',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 51,
          'address': '',
          'lng': '0',
          'idle': 35,
          'contactName': '',
          'busy': 16,
          'name': '\t洪泽湖路（世纪大道至平安大道）南',
          'keyId': '84',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 50,
          'address': '',
          'lng': '118.276915',
          'idle': 45,
          'contactName': '',
          'busy': 5,
          'name': '发展大道（厦门路至汕头路）西',
          'keyId': '83',
          'contactPhone': '',
          'lat': '33.928679'
        }, {
          'total': 49,
          'address': '',
          'lng': '118.275409',
          'idle': 32,
          'contactName': '',
          'busy': 17,
          'name': '青岛路（发展大道至人民大道）',
          'keyId': '123',
          'contactPhone': '',
          'lat': '33.9386'
        }, {
          'total': 49,
          'address': '',
          'lng': '118.261676',
          'idle': 39,
          'contactName': '',
          'busy': 10,
          'name': '太湖路（世纪大道至迎宾大道）',
          'keyId': '129',
          'contactPhone': '',
          'lat': '33.958461'
        }, {
          'total': 48,
          'address': '',
          'lng': '118.279694',
          'idle': 35,
          'contactName': '',
          'busy': 13,
          'name': '项王路（发展大道至富康大道）南',
          'keyId': '109',
          'contactPhone': '',
          'lat': '33.941725'
        }, {
          'total': 48,
          'address': '',
          'lng': '0',
          'idle': 21,
          'contactName': '',
          'busy': 27,
          'name': '洪泽湖路（发展大道至青年路）南侧',
          'keyId': '40',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 47,
          'address': '',
          'lng': '118.285483',
          'idle': 34,
          'contactName': '',
          'busy': 13,
          'name': '富康东巷（西湖路至高宝湖路）西',
          'keyId': '63',
          'contactPhone': '',
          'lat': '33.954866'
        }, {
          'total': 46,
          'address': '',
          'lng': '118.287121',
          'idle': 28,
          'contactName': '',
          'busy': 18,
          'name': '南湖东路（农发行东巷至富康大道）',
          'keyId': '126',
          'contactPhone': '',
          'lat': '33.960036'
        }, {
          'total': 46,
          'address': '',
          'lng': '0',
          'idle': 17,
          'contactName': '',
          'busy': 29,
          'name': '洪泽湖路（青年路至发展大道）北侧',
          'keyId': '128',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 46,
          'address': '',
          'lng': '118.276433',
          'idle': 30,
          'contactName': '',
          'busy': 16,
          'name': '发展大道（汕头路至深圳路）西',
          'keyId': '82',
          'contactPhone': '',
          'lat': '33.923191'
        }, {
          'total': 45,
          'address': '',
          'lng': '118.285694',
          'idle': 21,
          'contactName': '',
          'busy': 24,
          'name': '宝龙西巷（西湖路至大连路）西',
          'keyId': '145',
          'contactPhone': '',
          'lat': '33.949596'
        }, {
          'total': 44,
          'address': '',
          'lng': '118.261574',
          'idle': 40,
          'contactName': '',
          'busy': 4,
          'name': '\t千岛湖路（世纪大道至迎宾大道）',
          'keyId': '119',
          'contactPhone': '',
          'lat': '33.962741'
        }, {
          'total': 44,
          'address': '',
          'lng': '118.307158',
          'idle': 17,
          'contactName': '',
          'busy': 27,
          'name': '运河路（西湖路至马陵路）东',
          'keyId': '180',
          'contactPhone': '',
          'lat': '33.952185'
        }, {
          'total': 44,
          'address': '',
          'lng': '118.271496',
          'idle': 44,
          'contactName': '',
          'busy': 0,
          'name': '项王路（人民大道至平安大道）北',
          'keyId': '75',
          'contactPhone': '',
          'lat': '33.941936'
        }, {
          'total': 44,
          'address': '',
          'lng': '118.263698',
          'idle': 43,
          'contactName': '',
          'busy': 1,
          'name': '世纪大道（青海湖路至项王路）西',
          'keyId': '162',
          'contactPhone': '',
          'lat': '33.946336'
        }, {
          'total': 43,
          'address': '',
          'lng': '118.29228',
          'idle': 19,
          'contactName': '',
          'busy': 24,
          'name': '饮马堤路（项王路至杨公路）东',
          'keyId': '176',
          'contactPhone': '',
          'lat': '33.936794'
        }, {
          'total': 43,
          'address': '',
          'lng': '118.294879',
          'idle': 32,
          'contactName': '',
          'busy': 11,
          'name': '黄河路（洪泽湖路至八一路）东',
          'keyId': '81',
          'contactPhone': '',
          'lat': '33.961406'
        }, {
          'total': 43,
          'address': '',
          'lng': '118.281717',
          'idle': 27,
          'contactName': '',
          'busy': 16,
          'name': '仁恒北巷（文汇巷至富康大道）',
          'keyId': '132',
          'contactPhone': '',
          'lat': '33.958105'
        }, {
          'total': 42,
          'address': '',
          'lng': '118.279582',
          'idle': 41,
          'contactName': '',
          'busy': 1,
          'name': '发展大道（八一路至骆马湖路）西',
          'keyId': '70',
          'contactPhone': '',
          'lat': '33.968235'
        }, {
          'total': 42,
          'address': '',
          'lng': '118.279915',
          'idle': 19,
          'contactName': '',
          'busy': 23,
          'name': '\t高宝湖路（发展大道至劳动西巷）',
          'keyId': '127',
          'contactPhone': '',
          'lat': '33.953206'
        }, {
          'total': 41,
          'address': '',
          'lng': '118.332115',
          'idle': 41,
          'contactName': '',
          'busy': 0,
          'name': '江山大道（韶山路至项王路）西',
          'keyId': '39',
          'contactPhone': '',
          'lat': '33.944155'
        }, {
          'total': 41,
          'address': '',
          'lng': '0',
          'idle': 14,
          'contactName': '',
          'busy': 27,
          'name': '洪泽湖路（世纪大道至迎宾大道）北侧',
          'keyId': '118',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 41,
          'address': '',
          'lng': '118.332158',
          'idle': 41,
          'contactName': '',
          'busy': 0,
          'name': '\t江山大道（项王路至韶山路）东',
          'keyId': '101',
          'contactPhone': '',
          'lat': '33.944819'
        }, {
          'total': 40,
          'address': '',
          'lng': '118.259489',
          'idle': 19,
          'contactName': '',
          'busy': 21,
          'name': '微山湖路（迎宾大道至世纪大道）南',
          'keyId': '172',
          'contactPhone': '',
          'lat': '33.95453'
        }, {
          'total': 40,
          'address': '',
          'lng': '118.335339',
          'idle': 30,
          'contactName': '',
          'busy': 10,
          'name': '项王路(黄浦江路至江山大道)北',
          'keyId': '56',
          'contactPhone': '',
          'lat': '33.942062'
        }, {
          'total': 39,
          'address': '',
          'lng': '118.295188',
          'idle': 37,
          'contactName': '',
          'busy': 2,
          'name': '黄河路（八一路至宿支路）东',
          'keyId': '92',
          'contactPhone': '',
          'lat': '33.966494'
        }, {
          'total': 38,
          'address': '',
          'lng': '118.264278',
          'idle': 31,
          'contactName': '',
          'busy': 7,
          'name': '世纪大道（青海湖路至微山湖路）东',
          'keyId': '154',
          'contactPhone': '',
          'lat': '33.952513'
        }, {
          'total': 38,
          'address': '',
          'lng': '118.276954',
          'idle': 25,
          'contactName': '',
          'busy': 13,
          'name': '发展大道（汕头路至厦门路）东',
          'keyId': '100',
          'contactPhone': '',
          'lat': '33.927028'
        }, {
          'total': 38,
          'address': '',
          'lng': '118.270477',
          'idle': 38,
          'contactName': '',
          'busy': 0,
          'name': '项王路（平安大道至人民大道）南',
          'keyId': '112',
          'contactPhone': '',
          'lat': '33.942035'
        }, {
          'total': 37,
          'address': '',
          'lng': '118.265948',
          'idle': 28,
          'contactName': '',
          'busy': 9,
          'name': '微山湖路（世纪大道至平安大道）南',
          'keyId': '173',
          'contactPhone': '',
          'lat': '33.953444'
        }, {
          'total': 37,
          'address': '',
          'lng': '118.284387',
          'idle': 28,
          'contactName': '',
          'busy': 9,
          'name': '\t富康大道（南湖东路至骆马湖路）',
          'keyId': '131',
          'contactPhone': '',
          'lat': '33.961459'
        }, {
          'total': 37,
          'address': '',
          'lng': '118.279271',
          'idle': 30,
          'contactName': '',
          'busy': 7,
          'name': '发展大道（洪泽湖路至骆马湖路）东侧',
          'keyId': '32',
          'contactPhone': '',
          'lat': '33.96202'
        }, {
          'total': 37,
          'address': '',
          'lng': '118.277715',
          'idle': 20,
          'contactName': '',
          'busy': 17,
          'name': '发展大道（项王路至西湖路）东',
          'keyId': '99',
          'contactPhone': '',
          'lat': '33.946175'
        }, {
          'total': 36,
          'address': '',
          'lng': '118.279083',
          'idle': 17,
          'contactName': '',
          'busy': 19,
          'name': '项王路（富康大道至发展大道）北',
          'keyId': '108',
          'contactPhone': '',
          'lat': '33.941863'
        }, {
          'total': 35,
          'address': '',
          'lng': '118.264085',
          'idle': 30,
          'contactName': '',
          'busy': 5,
          'name': '世纪大道（微山湖路至青海湖路）西',
          'keyId': '161',
          'contactPhone': '',
          'lat': '33.95084'
        }, {
          'total': 34,
          'address': '',
          'lng': '118.277814',
          'idle': 27,
          'contactName': '',
          'busy': 7,
          'name': '发展大道（微山湖路至西湖路）西',
          'keyId': '98',
          'contactPhone': '',
          'lat': '33.950187'
        }, {
          'total': 34,
          'address': '',
          'lng': '118.277544',
          'idle': 24,
          'contactName': '',
          'busy': 10,
          'name': '\t发展大道（西湖路至项王路）西',
          'keyId': '97',
          'contactPhone': '',
          'lat': '33.945463'
        }, {
          'total': 34,
          'address': '',
          'lng': '118.262794',
          'idle': 20,
          'contactName': '',
          'busy': 14,
          'name': '微山湖路（世纪大道至迎宾大道）北',
          'keyId': '171',
          'contactPhone': '',
          'lat': '33.953943'
        }, {
          'total': 34,
          'address': '',
          'lng': '118.277226',
          'idle': 27,
          'contactName': '',
          'busy': 7,
          'name': '发展大道（青岛路至浦东路）西侧',
          'keyId': '74',
          'contactPhone': '',
          'lat': '33.936412'
        }, {
          'total': 33,
          'address': '',
          'lng': '118.331965',
          'idle': 32,
          'contactName': '',
          'busy': 1,
          'name': '江山大道（五台山路至洪泽湖路）西',
          'keyId': '65',
          'contactPhone': '',
          'lat': '33.955217'
        }, {
          'total': 33,
          'address': '',
          'lng': '118.268909',
          'idle': 29,
          'contactName': '',
          'busy': 4,
          'name': '微山湖路（平安大道至世纪大道）北',
          'keyId': '170',
          'contactPhone': '',
          'lat': '33.95291'
        }, {
          'total': 32,
          'address': '',
          'lng': '0',
          'idle': 30,
          'contactName': '',
          'busy': 2,
          'name': '洪泽湖路（人民大道至发展大道）南',
          'keyId': '96',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 32,
          'address': '',
          'lng': '118.290291',
          'idle': 20,
          'contactName': '',
          'busy': 12,
          'name': '黄河北路（宿支路至城北路）东侧',
          'keyId': '207',
          'contactPhone': '',
          'lat': '33.976173'
        }, {
          'total': 32,
          'address': '',
          'lng': '118.275779',
          'idle': 25,
          'contactName': '',
          'busy': 7,
          'name': '发展大道（深圳路至北京路）西',
          'keyId': '95',
          'contactPhone': '',
          'lat': '33.920044'
        }, {
          'total': 32,
          'address': '',
          'lng': '118.295215',
          'idle': 24,
          'contactName': '',
          'busy': 8,
          'name': '黄河路（宿支路至八一路）西',
          'keyId': '64',
          'contactPhone': '',
          'lat': '33.96887'
        }, {
          'total': 31,
          'address': '',
          'lng': '118.271483',
          'idle': 8,
          'contactName': '',
          'busy': 23,
          'name': '平安大道（洪泽湖路至骆马湖路）东',
          'keyId': '152',
          'contactPhone': '',
          'lat': '33.963145'
        }, {
          'total': 31,
          'address': '',
          'lng': '118.292451',
          'idle': 21,
          'contactName': '',
          'busy': 10,
          'name': '饮马堤路（卫生路至项王路）西',
          'keyId': '178',
          'contactPhone': '',
          'lat': '33.945107'
        }, {
          'total': 30,
          'address': '',
          'lng': '118.279496',
          'idle': 30,
          'contactName': '',
          'busy': 0,
          'name': '发展大道（骆马湖路至八一路）东',
          'keyId': '69',
          'contactPhone': '',
          'lat': '33.964806'
        }, {
          'total': 30,
          'address': '',
          'lng': '118.332053',
          'idle': 30,
          'contactName': '',
          'busy': 0,
          'name': '江山大道（井冈山路至韶山路）西',
          'keyId': '136',
          'contactPhone': '',
          'lat': '33.947871'
        }, {
          'total': 28,
          'address': '',
          'lng': '118.284603',
          'idle': 28,
          'contactName': '',
          'busy': 0,
          'name': '项王路（青年路至富康大道）北',
          'keyId': '48',
          'contactPhone': '',
          'lat': '33.94173'
        }, {
          'total': 28,
          'address': '',
          'lng': '118.275098',
          'idle': 28,
          'contactName': '',
          'busy': 0,
          'name': '项王路（发展大道至人民大道）北',
          'keyId': '113',
          'contactPhone': '',
          'lat': '33.941871'
        }, {
          'total': 28,
          'address': '',
          'lng': '118.275795',
          'idle': 26,
          'contactName': '',
          'busy': 2,
          'name': '发展大道（北京路至深圳路）东',
          'keyId': '94',
          'contactPhone': '',
          'lat': '33.919514'
        }, {
          'total': 28,
          'address': '',
          'lng': '118.292853804',
          'idle': 11,
          'contactName': '',
          'busy': 17,
          'name': '花园路（西湖路至卫生路）西侧',
          'keyId': '196',
          'contactPhone': '',
          'lat': '33.95080533'
        }, {
          'total': 27,
          'address': '',
          'lng': '118.269488',
          'idle': 15,
          'contactName': '',
          'busy': 12,
          'name': '太湖路（世纪大道至平安大道）南 ',
          'keyId': '163',
          'contactPhone': '',
          'lat': '33.957894'
        }, {
          'total': 26,
          'address': '',
          'lng': '118.277029',
          'idle': 8,
          'contactName': '',
          'busy': 18,
          'name': '发展大道（浦东路至厦门路）西',
          'keyId': '37',
          'contactPhone': '',
          'lat': '33.931729'
        }, {
          'total': 26,
          'address': '',
          'lng': '0',
          'idle': 23,
          'contactName': '',
          'busy': 3,
          'name': '洪泽湖路（人民大道至平安大道）北',
          'keyId': '93',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 26,
          'address': '',
          'lng': '118.274427',
          'idle': 26,
          'contactName': '',
          'busy': 0,
          'name': '项王路（人民大道至发展大道）南',
          'keyId': '107',
          'contactPhone': '',
          'lat': '33.94176'
        }, {
          'total': 25,
          'address': '',
          'lng': '118.266779',
          'idle': 18,
          'contactName': '',
          'busy': 7,
          'name': '洞庭湖路（世纪大道至平安大道）南',
          'keyId': '148',
          'contactPhone': '',
          'lat': '33.956306'
        }, {
          'total': 25,
          'address': '',
          'lng': '118.294511',
          'idle': 18,
          'contactName': '',
          'busy': 7,
          'name': '黄河路（洪泽湖路至渔市口路）西',
          'keyId': '53',
          'contactPhone': '',
          'lat': '33.956723'
        }, {
          'total': 24,
          'address': '',
          'lng': '118.271312',
          'idle': 20,
          'contactName': '',
          'busy': 4,
          'name': '微山湖路（平安大道至人民大道）南',
          'keyId': '174',
          'contactPhone': '',
          'lat': '33.952501'
        }, {
          'total': 24,
          'address': '',
          'lng': '118.281772',
          'idle': 20,
          'contactName': '',
          'busy': 4,
          'name': '\t南湖东路（富康大道至豪域西巷）',
          'keyId': '122',
          'contactPhone': '',
          'lat': '33.961215'
        }, {
          'total': 24,
          'address': '',
          'lng': '118.332154',
          'idle': 23,
          'contactName': '',
          'busy': 1,
          'name': '江山大道（韶山路至井岗山路）东',
          'keyId': '76',
          'contactPhone': '',
          'lat': '33.948511'
        }, {
          'total': 24,
          'address': '',
          'lng': '118.326236',
          'idle': 11,
          'contactName': '',
          'busy': 13,
          'name': '\t项王路（松花江路至珠江路）南',
          'keyId': '111',
          'contactPhone': '',
          'lat': '33.942036'
        }, {
          'total': 24,
          'address': '',
          'lng': '118.279094',
          'idle': 15,
          'contactName': '',
          'busy': 9,
          'name': '发展大道（骆马湖路至南湖路）西',
          'keyId': '102',
          'contactPhone': '',
          'lat': '33.962808'
        }, {
          'total': 23,
          'address': '',
          'lng': '118.279952',
          'idle': 10,
          'contactName': '',
          'busy': 13,
          'name': '文汇巷（微山湖路至高宝湖路）',
          'keyId': '120',
          'contactPhone': '',
          'lat': '33.951493'
        }, {
          'total': 23,
          'address': '',
          'lng': '118.293911',
          'idle': 20,
          'contactName': '',
          'busy': 3,
          'name': '项王路（黄河路至饮马堤路）北',
          'keyId': '41',
          'contactPhone': '',
          'lat': '33.941907'
        }, {
          'total': 23,
          'address': '',
          'lng': '118.277538',
          'idle': 22,
          'contactName': '',
          'busy': 1,
          'name': '发展大道（青岛路至项王路）东',
          'keyId': '52',
          'contactPhone': '',
          'lat': '33.941133'
        }, {
          'total': 23,
          'address': '',
          'lng': '118.264955',
          'idle': 21,
          'contactName': '',
          'busy': 2,
          'name': '世纪大道（千岛湖路至太湖路）西侧',
          'keyId': '133',
          'contactPhone': '',
          'lat': '33.959591'
        }, {
          'total': 22,
          'address': '',
          'lng': '118.264492',
          'idle': 21,
          'contactName': '',
          'busy': 1,
          'name': '世纪大道（洞庭湖路至微山湖路）西',
          'keyId': '160',
          'contactPhone': '',
          'lat': '33.954773'
        }, {
          'total': 22,
          'address': '',
          'lng': '0',
          'idle': 13,
          'contactName': '',
          'busy': 9,
          'name': '\t洪泽湖路（发展大道至人民大道）北',
          'keyId': '91',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 22,
          'address': '',
          'lng': '118.286996',
          'idle': 20,
          'contactName': '',
          'busy': 2,
          'name': '项王路（饮马堤路至花园路）北',
          'keyId': '45',
          'contactPhone': '',
          'lat': '33.941769'
        }, {
          'total': 22,
          'address': '',
          'lng': '118.279872',
          'idle': 20,
          'contactName': '',
          'busy': 2,
          'name': '发展大道（宿支路至八一路）西',
          'keyId': '68',
          'contactPhone': '',
          'lat': '33.971147'
        }, {
          'total': 22,
          'address': '',
          'lng': '118.27717',
          'idle': 18,
          'contactName': '',
          'busy': 4,
          'name': '微山湖路（发展大道至人民大道）北',
          'keyId': '168',
          'contactPhone': '',
          'lat': '33.951504'
        }, {
          'total': 22,
          'address': '',
          'lng': '118.264836',
          'idle': 21,
          'contactName': '',
          'busy': 1,
          'name': '世纪大道（洞庭湖路至太湖路）东',
          'keyId': '156',
          'contactPhone': '',
          'lat': '33.957675'
        }, {
          'total': 22,
          'address': '',
          'lng': '118.262406',
          'idle': 18,
          'contactName': '',
          'busy': 4,
          'name': '法苑巷（洪泽湖路至千岛湖路）',
          'keyId': '115',
          'contactPhone': '',
          'lat': '33.961117'
        }, {
          'total': 21,
          'address': '',
          'lng': '118.306922',
          'idle': 18,
          'contactName': '',
          'busy': 3,
          'name': '运河路（马陵路至西湖路）西',
          'keyId': '181',
          'contactPhone': '',
          'lat': '33.951668'
        }, {
          'total': 21,
          'address': '',
          'lng': '118.292473',
          'idle': 13,
          'contactName': '',
          'busy': 8,
          'name': '饮马堤路（项王路至卫生路）东',
          'keyId': '177',
          'contactPhone': '',
          'lat': '33.945071'
        }, {
          'total': 21,
          'address': '',
          'lng': '118.27828',
          'idle': 18,
          'contactName': '',
          'busy': 3,
          'name': '发展大道（微山湖路至洞庭湖路）东',
          'keyId': '72',
          'contactPhone': '',
          'lat': '33.953449'
        }, {
          'total': 21,
          'address': '',
          'lng': '118.293085',
          'idle': 11,
          'contactName': '',
          'busy': 10,
          'name': '项王路（饮马堤路至黄河路）南',
          'keyId': '42',
          'contactPhone': '',
          'lat': '33.941849'
        }, {
          'total': 21,
          'address': '',
          'lng': '118.340039',
          'idle': 18,
          'contactName': '',
          'busy': 3,
          'name': '项王路（西楚大道至黄浦江路）北',
          'keyId': '54',
          'contactPhone': '',
          'lat': '33.942049'
        }, {
          'total': 20,
          'address': '',
          'lng': '118.277367',
          'idle': 17,
          'contactName': '',
          'busy': 3,
          'name': '发展大道（浦东路至青岛路）东',
          'keyId': '47',
          'contactPhone': '',
          'lat': '33.937043'
        }, {
          'total': 20,
          'address': '',
          'lng': '118.280142',
          'idle': 8,
          'contactName': '',
          'busy': 12,
          'name': '文汇巷（高宝湖路至洞庭湖路）东',
          'keyId': '35',
          'contactPhone': '',
          'lat': '33.953648'
        }, {
          'total': 20,
          'address': '',
          'lng': '118.267261',
          'idle': 20,
          'contactName': '',
          'busy': 0,
          'name': '\t项王路（世纪大道至平安大道）南',
          'keyId': '110',
          'contactPhone': '',
          'lat': '33.942103'
        }, {
          'total': 20,
          'address': '',
          'lng': '118.339079',
          'idle': 8,
          'contactName': '',
          'busy': 12,
          'name': '项王路（学海路至西楚大道）南',
          'keyId': '51',
          'contactPhone': '',
          'lat': '33.941969'
        }, {
          'total': 20,
          'address': '',
          'lng': '118.275025',
          'idle': 14,
          'contactName': '',
          'busy': 6,
          'name': '微山湖路（人民大道至发展大道）南',
          'keyId': '175',
          'contactPhone': '',
          'lat': '33.95186'
        }, {
          'total': 20,
          'address': '',
          'lng': '118.265222',
          'idle': 17,
          'contactName': '',
          'busy': 3,
          'name': '世纪大道（洪泽湖路至千岛湖路）东',
          'keyId': '158',
          'contactPhone': '',
          'lat': '33.96159'
        }, {
          'total': 20,
          'address': '',
          'lng': '118.334132',
          'idle': 11,
          'contactName': '',
          'busy': 9,
          'name': '项王路（江山大道至学海路）南',
          'keyId': '50',
          'contactPhone': '',
          'lat': '33.942013'
        }, {
          'total': 20,
          'address': '',
          'lng': '118.287526',
          'idle': 6,
          'contactName': '',
          'busy': 14,
          'name': '农发行东巷（太湖路至洪泽湖路）',
          'keyId': '134',
          'contactPhone': '',
          'lat': '33.956464'
        }, {
          'total': 19,
          'address': '',
          'lng': '118.267716',
          'idle': 9,
          'contactName': '',
          'busy': 10,
          'name': '建设西巷',
          'keyId': '66',
          'contactPhone': '',
          'lat': '33.959173'
        }, {
          'total': 19,
          'address': '',
          'lng': '118.332121',
          'idle': 11,
          'contactName': '',
          'busy': 8,
          'name': '江山大道（井冈山路至洪泽湖路）东',
          'keyId': '89',
          'contactPhone': '',
          'lat': '33.950488'
        }, {
          'total': 18,
          'address': '',
          'lng': '0',
          'idle': 17,
          'contactName': '',
          'busy': 1,
          'name': '洪泽湖路(平安大道至人民大道)南',
          'keyId': '88',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 18,
          'address': '',
          'lng': '118.277361',
          'idle': 9,
          'contactName': '',
          'busy': 9,
          'name': '发展大道（项王路至青岛路）西',
          'keyId': '58',
          'contactPhone': '',
          'lat': '33.940314'
        }, {
          'total': 18,
          'address': '',
          'lng': '118.280623',
          'idle': 12,
          'contactName': '',
          'busy': 6,
          'name': '文汇巷(太湖路至洪泽湖路)',
          'keyId': '116',
          'contactPhone': '',
          'lat': '33.958007'
        }, {
          'total': 18,
          'address': '',
          'lng': '118.272154',
          'idle': 14,
          'contactName': '',
          'busy': 4,
          'name': '洞庭湖路（人民大道至平安大道）北',
          'keyId': '147',
          'contactPhone': '',
          'lat': '33.956003'
        }, {
          'total': 18,
          'address': '',
          'lng': '118.275876',
          'idle': 15,
          'contactName': '',
          'busy': 3,
          'name': '国泰西巷（青海湖路至微山湖路）东',
          'keyId': '150',
          'contactPhone': '',
          'lat': '33.950557'
        }, {
          'total': 18,
          'address': '',
          'lng': '118.324152',
          'idle': 15,
          'contactName': '',
          'busy': 3,
          'name': '项王路(西湖路至松花江路)北',
          'keyId': '79',
          'contactPhone': '',
          'lat': '33.942149'
        }, {
          'total': 18,
          'address': '',
          'lng': '118.284445111',
          'idle': 6,
          'contactName': '',
          'busy': 12,
          'name': '大连路（富康大道至青年路）南侧',
          'keyId': '193',
          'contactPhone': '',
          'lat': '33.945007422'
        }, {
          'total': 16,
          'address': '',
          'lng': '118.272922',
          'idle': 15,
          'contactName': '',
          'busy': 1,
          'name': '微山湖路（人民大道至平安大道）北',
          'keyId': '169',
          'contactPhone': '',
          'lat': '33.952216'
        }, {
          'total': 16,
          'address': '',
          'lng': '118.332094',
          'idle': 13,
          'contactName': '',
          'busy': 3,
          'name': '江山大道（洪泽湖路至井冈山路）西',
          'keyId': '33',
          'contactPhone': '',
          'lat': '33.951249'
        }, {
          'total': 16,
          'address': '',
          'lng': '118.329643',
          'idle': 8,
          'contactName': '',
          'busy': 8,
          'name': '项王路（珠江路至江山大道）南',
          'keyId': '78',
          'contactPhone': '',
          'lat': '33.942032'
        }, {
          'total': 16,
          'address': '',
          'lng': '118.322108',
          'idle': 12,
          'contactName': '',
          'busy': 4,
          'name': '项王路（长江路至松花江路）南',
          'keyId': '34',
          'contactPhone': '',
          'lat': '33.942184'
        }, {
          'total': 15,
          'address': '',
          'lng': '118.319182',
          'idle': 8,
          'contactName': '',
          'busy': 7,
          'name': '项王路(长江路至九龙江路)北',
          'keyId': '44',
          'contactPhone': '',
          'lat': '33.942094'
        }, {
          'total': 15,
          'address': '',
          'lng': '118.264988',
          'idle': 14,
          'contactName': '',
          'busy': 1,
          'name': '世纪大道（太湖路至洪泽湖路）东',
          'keyId': '157',
          'contactPhone': '',
          'lat': '33.958913'
        }, {
          'total': 15,
          'address': '',
          'lng': '118.278774',
          'idle': 13,
          'contactName': '',
          'busy': 2,
          'name': '发展大道（太湖路至洪泽湖路）东侧',
          'keyId': '121',
          'contactPhone': '',
          'lat': '33.957851'
        }, {
          'total': 15,
          'address': '',
          'lng': '118.285966',
          'idle': 10,
          'contactName': '',
          'busy': 5,
          'name': '\t年华东巷（南湖东路至洪泽湖路）',
          'keyId': '125',
          'contactPhone': '',
          'lat': '33.959557'
        }, {
          'total': 15,
          'address': '',
          'lng': '118.294507',
          'idle': 6,
          'contactName': '',
          'busy': 9,
          'name': '\t黄河路（渔市口路至洪泽湖路）东',
          'keyId': '43',
          'contactPhone': '',
          'lat': '33.955472'
        }, {
          'total': 15,
          'address': '',
          'lng': '118.284941',
          'idle': 10,
          'contactName': '',
          'busy': 5,
          'name': '富康东巷（西湖路至高宝湖路）东',
          'keyId': '71',
          'contactPhone': '',
          'lat': '33.951392'
        }, {
          'total': 15,
          'address': '',
          'lng': '118.269446',
          'idle': 6,
          'contactName': '',
          'busy': 9,
          'name': '太湖路（平安大道至世纪大道）北',
          'keyId': '167',
          'contactPhone': '',
          'lat': '33.957912'
        }, {
          'total': 14,
          'address': '',
          'lng': '118.28801',
          'idle': 12,
          'contactName': '',
          'busy': 2,
          'name': '农发行东巷（洪泽湖路至南湖东路）',
          'keyId': '130',
          'contactPhone': '',
          'lat': '33.959004'
        }, {
          'total': 14,
          'address': '',
          'lng': '118.279993',
          'idle': 6,
          'contactName': '',
          'busy': 8,
          'name': '发展大道（八一路至宿支路）东',
          'keyId': '67',
          'contactPhone': '',
          'lat': '33.969819'
        }, {
          'total': 14,
          'address': '',
          'lng': '118.278499',
          'idle': 9,
          'contactName': '',
          'busy': 5,
          'name': '发展大道（太湖路至洞庭湖路）西',
          'keyId': '104',
          'contactPhone': '',
          'lat': '33.956846'
        }, {
          'total': 14,
          'address': '',
          'lng': '118.278654',
          'idle': 13,
          'contactName': '',
          'busy': 1,
          'name': '发展大道（洪泽湖路至太湖路）西',
          'keyId': '105',
          'contactPhone': '',
          'lat': '33.958261'
        }, {
          'total': 13,
          'address': '',
          'lng': '118.264707',
          'idle': 5,
          'contactName': '',
          'busy': 8,
          'name': '世纪大道（太湖路至洞庭湖路）西',
          'keyId': '159',
          'contactPhone': '',
          'lat': '33.956927'
        }, {
          'total': 13,
          'address': '',
          'lng': '118.264471',
          'idle': 13,
          'contactName': '',
          'busy': 0,
          'name': '世纪大道（微山湖路至洞庭湖路）东',
          'keyId': '155',
          'contactPhone': '',
          'lat': '33.955699'
        }, {
          'total': 12,
          'address': '',
          'lng': '118.275797',
          'idle': 10,
          'contactName': '',
          'busy': 2,
          'name': '太湖路（平安大道至人民大道）南',
          'keyId': '164',
          'contactPhone': '',
          'lat': '33.957467'
        }, {
          'total': 12,
          'address': '',
          'lng': '118.27793',
          'idle': 9,
          'contactName': '',
          'busy': 3,
          'name': '发展大道（西湖路至微山湖路）东',
          'keyId': '49',
          'contactPhone': '',
          'lat': '33.949762'
        }, {
          'total': 12,
          'address': '',
          'lng': '118.277412',
          'idle': 11,
          'contactName': '',
          'busy': 1,
          'name': '洞庭湖路（人民大道至发展大道）南',
          'keyId': '149',
          'contactPhone': '',
          'lat': '33.955656'
        }, {
          'total': 12,
          'address': '',
          'lng': '118.278257',
          'idle': 10,
          'contactName': '',
          'busy': 2,
          'name': '发展大道（微山湖路至高宝湖路）东侧',
          'keyId': '73',
          'contactPhone': '',
          'lat': '33.952605'
        }, {
          'total': 12,
          'address': '',
          'lng': '118.322111',
          'idle': 12,
          'contactName': '',
          'busy': 0,
          'name': '项王路(松花江路至长江路)北',
          'keyId': '59',
          'contactPhone': '',
          'lat': '33.942143'
        }, {
          'total': 12,
          'address': '',
          'lng': '118.271311',
          'idle': 2,
          'contactName': '',
          'busy': 10,
          'name': '平安大道（骆马湖路至洪泽湖路）西',
          'keyId': '153',
          'contactPhone': '',
          'lat': '33.961392'
        }, {
          'total': 11,
          'address': '',
          'lng': '118.278955',
          'idle': 11,
          'contactName': '',
          'busy': 0,
          'name': '发展大道（南湖路至洪泽湖路）西',
          'keyId': '103',
          'contactPhone': '',
          'lat': '33.961254'
        }, {
          'total': 11,
          'address': '',
          'lng': '118.275792',
          'idle': 7,
          'contactName': '',
          'busy': 4,
          'name': '洞庭湖路（发展大道至人民大道）北',
          'keyId': '146',
          'contactPhone': '',
          'lat': '33.955763'
        }, {
          'total': 11,
          'address': '',
          'lng': '118.285217',
          'idle': 11,
          'contactName': '',
          'busy': 0,
          'name': '\t项王路（富康大道至青年路）南',
          'keyId': '106',
          'contactPhone': '',
          'lat': '33.941662'
        }, {
          'total': 10,
          'address': '',
          'lng': '118.275774',
          'idle': 2,
          'contactName': '',
          'busy': 8,
          'name': '国泰西巷（微山湖路至青海湖路）西',
          'keyId': '151',
          'contactPhone': '',
          'lat': '33.949507'
        }, {
          'total': 9,
          'address': '',
          'lng': '118.277557',
          'idle': 6,
          'contactName': '',
          'busy': 3,
          'name': '太湖路（发展大道至人民大道）北',
          'keyId': '165',
          'contactPhone': '',
          'lat': '33.957324'
        }, {
          'total': 9,
          'address': '',
          'lng': '118.285517',
          'idle': 2,
          'contactName': '',
          'busy': 7,
          'name': '宝龙西巷（大连路至西湖路）东',
          'keyId': '144',
          'contactPhone': '',
          'lat': '33.945832'
        }, {
          'total': 9,
          'address': '',
          'lng': '118.330834',
          'idle': 9,
          'contactName': '',
          'busy': 0,
          'name': '项王路(江山大道至珠江路)北',
          'keyId': '80',
          'contactPhone': '',
          'lat': '33.942098'
        }, {
          'total': 8,
          'address': '',
          'lng': '0',
          'idle': 7,
          'contactName': '',
          'busy': 1,
          'name': '测试路段',
          'keyId': '25',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 8,
          'address': '',
          'lng': '118.277238',
          'idle': 8,
          'contactName': '',
          'busy': 0,
          'name': '发展大道（厦门路至浦东路）东',
          'keyId': '36',
          'contactPhone': '',
          'lat': '33.93362'
        }, {
          'total': 7,
          'address': '',
          'lng': '118.286199338',
          'idle': 2,
          'contactName': '',
          'busy': 5,
          'name': '大连路（青年路至富康大道）北侧',
          'keyId': '192',
          'contactPhone': '',
          'lat': '33.944979876'
        }, {
          'total': 7,
          'address': '',
          'lng': '118.279145',
          'idle': 7,
          'contactName': '',
          'busy': 0,
          'name': '太湖路（发展大道至文汇巷）',
          'keyId': '124',
          'contactPhone': '',
          'lat': '33.957248'
        }, {
          'total': 6,
          'address': '',
          'lng': '118.273694',
          'idle': 5,
          'contactName': '',
          'busy': 1,
          'name': '太湖路（人民大道至平安大道）北',
          'keyId': '166',
          'contactPhone': '',
          'lat': '33.957609'
        }, {
          'total': 5,
          'address': '',
          'lng': '0',
          'idle': 1,
          'contactName': '',
          'busy': 4,
          'name': '升级测试工作点2',
          'keyId': '138',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 4,
          'address': '',
          'lng': '118.278552',
          'idle': 4,
          'contactName': '',
          'busy': 0,
          'name': '发展大道（洞庭湖路至太湖路）东',
          'keyId': '90',
          'contactPhone': '',
          'lat': '33.956071'
        }, {
          'total': 0,
          'address': '',
          'lng': '0',
          'idle': 0,
          'contactName': '',
          'busy': 0,
          'name': '002',
          'keyId': '13',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 0,
          'address': '',
          'lng': '0',
          'idle': 0,
          'contactName': '',
          'busy': 0,
          'name': '004',
          'keyId': '23',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 0,
          'address': '',
          'lng': '0',
          'idle': 0,
          'contactName': '',
          'busy': 0,
          'name': '003',
          'keyId': '16',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 0,
          'address': '',
          'lng': '0',
          'idle': 0,
          'contactName': '',
          'busy': 0,
          'name': '005',
          'keyId': '31',
          'contactPhone': '',
          'lat': '0'
        }, {
          'total': 0,
          'address': '',
          'lng': '1',
          'idle': 0,
          'contactName': '',
          'busy': 0,
          'name': '\t新华书城立体车库',
          'keyId': '114',
          'contactPhone': '',
          'lat': '1'
        }
      ]
      this.LMap.initMap('map')
      // this.map.addHeatMap(data, { blur: 8, radius: 10, weightCallBack: (e) => {
      //   return Number(e.get('data')['total']) / 70
      // } })
      this.addHeatMap(data)
    }, 1000)
  },
  methods: {
    addHeatMap(data) {
      // 热力图
      const option = {
        blur: 15,
        radius: 10,
        weightCallBack: (e) => { return Number(e.get('data')['total']) } // 70
      }

      const createFeature = (e) => {
        return new Feature({
          geometry: new Point(e.lnglat || [e.lng, e.lat] || e.position),
          data: e
        })
      }

      const features = []

      for (const i in data) {
        features.push(createFeature(data[i]))
      }
      const source = new VectorSource({})
      source.addFeatures(features)

      this.heatMapLayer = new HeatmapLayer({
        source: source,
        blur: option.blur || 5,
        radius: option.radius || 10,
        weight: (e) => {
          if (option.weightCallBack) {
            return option.weightCallBack(e)
          }
        }
      })

      this.LMap.map.addLayer(this.heatMapLayer)
    }
  }
}
</script>

<style scoped lang="scss">
  .map {
    width: 100%;
    height: calc(100vh - 84px);
    background: #1f2d3d;
  }
</style>
